### ISSUE TITLE
Translate in another language

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [samuel-s-marques/todo-app#5]
I would like to translate the app into German, where can I find the strings?

**Comment by samuel-s-marques** [comment]
Hey. The translation to German is already in progress. But it would be great if you take a look at it. 

Here, [de.json](https://github.com/samuel-s-marques/todo-app/blob/v1.0.2/assets/i18n/de.json). I'm not German, so I don't know if anything is correct, as I used [Deepl](deepl.com/).

**Comment by mondlicht-und-sterne** [comment]
> Hey. The translation to German is already in progress. But it would be great if you take a look at it.
> 
> Here, [de.json](https://github.com/samuel-s-marques/todo-app/blob/v1.0.2/assets/i18n/de.json). I'm not German, so I don't know if anything is correct, as I used [Deepl](deepl.com/).

@samuel-s-marques   But I can't do a pull request. I will write the changed version afterwards.

**Comment by mondlicht-und-sterne** [comment]
hi @samuel-s-marques 

here i have an updated [german ](https://github.com/mondlicht-und-sterne/Translations/blob/main/todo.de.json)translation

**you must only rename it from todo.de.json to de.json**
